version: '3.7'
services:
    admin_bot:
        container_name: admin_bot
        image: tk/code-exp-admin-bot:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        restart: unless-stopped
